name: Terraform CI/CD Pipeline

on:
  push:
    branches:
      - main  # Trigger the pipeline on push to the main branch

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.9.8

      - name: Configure Terraform Cloud API Token
        run: echo "TFC_CLOUD_TOKEN=${{ secrets.TFC_CLOUD_TOKEN }}" >> $GITHUB_ENV  # Set the API token as an environment variable

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply -auto-approve
        env:
          TFC_CLOUD_TOKEN: ${{ secrets.TFC_CLOUD_TOKEN }}  # Use the stored Terraform Cloud API token during apply
