name: Terraform EC2 Deployment

on:
  workflow_dispatch:  # Allows you to trigger this workflow manually from GitHub UI

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.9.8  # Specify the Terraform version you need

      - name: Authenticate with Terraform Cloud
        env:
          TFE_TOKEN: ${{ secrets.TFE_TOKEN }}
        run: terraform login

      - name: Initialize Terraform
        run: terraform init

      - name: Terraform Plan
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ap-south-1
        run: terraform plan

      - name: Terraform Apply
        if: github.event.inputs.approve == 'true'  # Optional conditional for manual approval
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ap-south-1
        run: terraform apply -auto-approve
